directories:
  output: release
  buildResources: build
appId: com.converter.app
productName: 精转数智
asar: true
asarUnpack:
  - python-dist/**/*
files:
  - filter:
      - dist/**/*
      - node_modules/**/*
      - scripts/**/*
      - package.json
      - '!node_modules/**/*.{md,txt,LICENSE,CHANGELOG,CHANGELOG.md}'
      - '!node_modules/**/test/**/*'
      - '!node_modules/**/tests/**/*'
      - '!node_modules/**/*.d.ts'
      - '!node_modules/**/.git/**/*'
      - '!node_modules/**/docs/**/*'
      - '!node_modules/**/documentation/**/*'
      - '!node_modules/**/examples/**/*'
      - '!node_modules/**/example/**/*'
      - '!node_modules/**/.nyc_output/**/*'
      - '!node_modules/**/coverage/**/*'
      - '!node_modules/**/*.map'
      - '!node_modules/**/README*'
      - '!node_modules/**/readme*'
      - '!node_modules/**/HISTORY*'
      - '!node_modules/**/CONTRIBUTORS*'
      - '!node_modules/**/AUTHORS*'
      - '!node_modules/**/.eslintrc*'
      - '!node_modules/**/.jshintrc*'
      - '!node_modules/**/.travis.yml'
      - '!node_modules/**/Makefile'
      - '!node_modules/**/makefile'
      - '!node_modules/**/*.coffee'
      - '!node_modules/**/*.flow'
extraResources:
  - from: assets
    to: assets
    filter:
      - '**/*'
  - from: python-dist
    to: python-dist
    filter:
      - '**/*'
mac:
  category: public.app-category.productivity
  icon: build/icon.icns
  target:
    - target: dmg
      arch:
        - x64
win:
  icon: build/icon.ico
  target:
    - target: nsis
      arch:
        - x64
linux:
  icon: build/icon.png
  target:
    - target: AppImage
      arch:
        - x64
    - target: deb
      arch:
        - x64
    - target: rpm
      arch:
        - x64
  category: Office
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
electronVersion: 37.2.3
