directories:
  output: release
  buildResources: build
appId: com.converter.app
productName: 精转数智
files:
  - filter:
      - dist/**/*
      - node_modules/**/*
      - '!node_modules/**/*.{md,txt,LICENSE}'
      - '!node_modules/**/test/**/*'
      - '!node_modules/**/*.d.ts'
extraResources:
  - from: assets
    to: assets
    filter:
      - '**/*'
mac:
  category: public.app-category.productivity
  icon: build/icon.icns
  target:
    - target: dmg
      arch:
        - x64
        - arm64
    - target: zip
      arch:
        - x64
        - arm64
win:
  icon: build/icon.ico
  target:
    - target: nsis
      arch:
        - x64
        - ia32
    - target: portable
      arch:
        - x64
linux:
  icon: build/icon.png
  target:
    - target: AppImage
      arch:
        - x64
    - target: deb
      arch:
        - x64
    - target: rpm
      arch:
        - x64
  category: Office
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
electronVersion: 37.2.3
